### PR TITLE
6 web xr spike

### PR DESCRIPTION
**Pull request by Jesster2829**
Just a foundation for the project for us to start, Approve when ready

### CODE REVIEW

**Review by MitchWag01 — APPROVED** [review]
Looks good, lets just make sure to set code standards so that everything follows

**Review by MitchWag01 — APPROVED** [review]

**Review by trangnguyen3010 — COMMENTED** [review]
do we want to move everything from my-webxr-app to the root folder? just so we don't have an extra layer of folder?

**Review by trangnguyen3010 — COMMENTED** [review]
minor: it'll be nice to have short instructions on npm commands to start/build/test... this project in README.md so that anyone can easily run the app after going through the README.

**Review by trangnguyen3010 — COMMENTED** [review]
minor: for future branches and commits, please prefix their name with `#<issueNumber>` as per [our Branching Strategy doc](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Branching-Strategy). No worries about changing anything for this one though since we only rolled out the doc after you kicked off this branch! 🙈

Update: actually, can you please update the branch name and commit messages? 🥺  (should be quick enough through WebStorm UI or even git cli)
Screenshot 2024-01-26 at 10 19 11 AM

**Comment by trangnguyen3010** [comment]
@Jesster2829 @MitchWag01 heyy, just wondering if you have seen my previous comments 🥺 No pressure on reopen the PR in any way, I just want to ensure they didn't slip through the cracks.

**Pull request merged**
