### PR TITLE
11: parse csv from url

### LINKED ISSUE #11: Parse CSV file from a URL
Add functionality to load a csv file from a provided url

### PR DESCRIPTION
**Pull request by LongQuanNguyen**
Closes #11 

# What was the issue
Implement a component to read CSV from URL and parse it into indexed DB

# What was done and why
- Install Papaparse to parse csv.
- Install idb to enable the use of indexedDB.
- Implement UrlCsvReader

# How it was tested
- Added unit tests
- Implement a UI pop-up message that only pops up when the CSV gets parsed and saves to the db successfully.
- Make use of assertions.

### CODE REVIEW

**Comment by LongQuanNguyen** [comment]
Writing unit tests for this is much harder than I thought. I therefore, send out this SOS message =(((

**Comment by LongQuanNguyen** [comment]
I split the function into smaller functions and put in place some unit tests. The coverage is not too high.

**Comment by matthew-buglass** [comment]
I fixed some merge conflicts from the merging of the local reader.

**Review by matthew-buglass — APPROVED** [review]
Looks good

**Pull request merged**
