### PR TITLE
#60 Fixed gherkin rebase to exclude .intelli

### PR DESCRIPTION
**Pull request by MitchWag01**
Fixed bad PR, and removed .intelli files that were originally in PR.

### CODE REVIEW

**Review by matthew-buglass — APPROVED** [review]

**Review by Subzeero — APPROVED** [review]

**Comment by MitchWag01** [comment]
[deliverable1 QA test.pdf](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/files/14078920/deliverable1.QA.test.pdf)

**Comment by matthew-buglass** [comment]
Add the pdf to the artifacts directory

**Review by matthew-buglass — CHANGES_REQUESTED** [review]
Add results pdf to the artifacts dir

**Review by matthew-buglass — APPROVED** [review]

**Comment by MitchWag01** [comment]
> Add results pdf to the artifacts dir

Added the QA ID1 test outputs to artifacts.

**Pull request merged**
