### PR TITLE
255: Merge and cut ID5

### LINKED ISSUE #255: Merge ID5 into master and cut the release

### PR DESCRIPTION
**Pull request by matthew-buglass**
Closes #255 

# What was the issue
- We need to merge the work that was done for ID5 into master and cut the release

# What was done and why
- Worked on integrating human-in-the-loop integration testing
- Built a full vertical slice of the system

# How it was tested
- @MitchWag01 please fill this in
[QA_Summary_and_Update.pdf](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/files/14860530/QA_Summary_and_Update.pdf)

### CODE REVIEW

**Comment by trangnguyen3010** [comment]
https://web-test.subzeero.dev/5by5.csv
https://web-test.subzeero.dev/box.csv
https://web-test.subzeero.dev/box_dup_headers.csv
https://web-test.subzeero.dev/box_missing_last_col.csv
https://web-test.subzeero.dev/0.csv
https://web-test.subzeero.dev/2000.csv
https://web-test.subzeero.dev/10000.csv
https://web-test.subzeero.dev/50000.csv
https://web-test.subzeero.dev/500000.csv
(renamed the others)

**Comment by matthew-buglass** [comment]
[Grand Activity Log - Demo Data.csv](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/files/14844378/Grand.Activity.Log.-.Demo.Data.csv)

**Review by trangnguyen3010 — APPROVED** [review]

**Review by Subzeero — APPROVED** [review]
There's no turning back now 🎉

**Review by Jesster2829 — APPROVED** [review]
Looks good

**Review by MitchWag01 — COMMENTED** [review]
congratulations on the final PR, all the documents to submit look like they are in, and I think its ready to go

**Review by MitchWag01 — APPROVED** [review]

**Pull request merged**
