### PR TITLE
3 test webhooks

### LINKED ISSUE #3: GitHub-Discord Webhooks
Look into GitHub-Discord Webhooks to get infrastructure notifications on the server

### PR DESCRIPTION
**Pull request by matthew-buglass**
THIS SHOULD NOT BE MERGED. I am testing webhooks.

Closes #3

### CODE REVIEW

**Comment by matthew-buglass** [comment]
is the webhook working now?

**Comment by matthew-buglass** [comment]
All three should fire

**Comment by matthew-buglass** [comment]
just PR should fire

**Comment by matthew-buglass** [comment]
pew

**Comment by matthew-buglass** [comment]
Pew?

**Comment by matthew-buglass** [comment]
Pew Pew

**Comment by matthew-buglass** [comment]
Victory?

**Comment by Joembonayo** [comment]
Hey, matt. Do we all have write access?

**Comment by matthew-buglass** [comment]
> Hey, matt. Do we all have write access?

Write access to which parts of the repo?

**Comment by matthew-buglass** [comment]
doot

**Comment by matthew-buglass** [comment]
doot doot

**Pull request closed without merging**
