### PR TITLE
#120: Writing Gherkin to test data processing of the PCA analysis

### LINKED ISSUE #120: Write Gherkin for PCA backend
Write and run the integration tests for the data processing backend of the PCA analysis. Tests work done in #24

### PR DESCRIPTION
**Pull request by Joembonayo**
Closes #120 

# What was the issue
Needed to write gherkin to test data processing of the PCA analysis.

# What was done and why
I wrote test scenarios to make sure the user has passed the necessary amount of data for the PCA analysis.
One for when there is the right amount of data to dispaly at least 3 PCAs and one for when there is not enough.

# How it was tested
We ran the test myself and mitchell by loading the project and they all passed

### CODE REVIEW

**Comment by matthew-buglass** [comment]
Can you direct this to the `release/ID4` branch?

**Review by matthew-buglass — CHANGES_REQUESTED** [review]
Can you direct this to the release/ID4 branch?

**Review by qpb948 — COMMENTED** [review]
Do you need a background section like the other gherkins?

**Comment by Joembonayo** [comment]
> Do you need a background section like the other gherkins?

I will do that. Thanks

**Review by qpb948 — APPROVED** [review]
Looks good now

**Comment by matthew-buglass** [comment]
This is still targeting the wrong branch. It needs to target `release/ID4`, as per our branching strategy.

**Review by matthew-buglass — APPROVED** [review]

**Pull request merged**
